### ISSUE TITLE
Canvas elements missing from SVG

### ISSUE THREAD

**Issue by op3** [felixfbecker/svg-screenshots#123]
I tried to create a screenshot of a page that contains several `<canvas>` elements. These elements are missing from the resulting SVG. The rational for this is given [here](https://github.com/felixfbecker/svg-screenshots/issues/13#issuecomment-725295975).

Obviously, including the canvas elements in the SVG is only possible as a raster image. However, I still think that including the raster images is beneficial in comparison to a pure raster screenshot: You retain all the other text elements and links that are included on the site. After all, other images are embedded as well.

Otherwise, this extension is working great, so I was surprised that parts of the screenshot I created were missing. Maybe this is something worth considering? Alternatively, I would suggest to add a small note to the README to mention that canvas elements are excluded.

**Comment by felixfbecker** [comment]
Agree, happy to accept a PR! It just wasn't implemented.

**Comment by op3** [comment]
I just realized that this should be implemented in [dom-to-svg](https://github.com/felixfbecker/dom-to-svg) instead. There is already a [corresponding issue](https://github.com/felixfbecker/dom-to-svg/issues/181), and the [workaround](https://github.com/felixfbecker/dom-to-svg/issues/181#issuecomment-2016049951) by @jkurkure works reasonably well. (Not sure if it’s useful for an actual implementation)
