### ISSUE TITLE
The extension doesn't work properly

### ISSUE THREAD

**Issue by ricknjacky** [felixfbecker/svg-screenshots#13]
The extension selects the specified area, however it doesn't do anything after it, like download the required .svg file

The behavior:- 

![extension](https://user-images.githubusercontent.com/50985033/98784878-c4d8df00-2421-11eb-8fa6-7bad86c25508.gif)

ps:- If there are some additional steps to be done after the selection, I think it'd be better to mention it in the readme file and the extension page :)

**Comment by felixfbecker** [comment]
Could you check if there are any errors in the console? Menu > More tools > Developer Tools > Console
It is likely that you are running into an error that has been fixed in the latest version, which is still in review by the Chrome web store.

**Comment by felixfbecker** [comment]
You could also try installing v0.0.2 directly and see if that fixes it for you: https://github.com/felixfbecker/svg-screenshots/releases/download/v0.0.2/svg-screenshots-chrome.zip

See here how to load it into Chrome without the store: https://developer.chrome.com/extensions/getstarted#manifest:~:text=Open%20the%20Extension%20Management%20page%20by,button%20and%20select%20the%20extension%20directory.

**Comment by ricknjacky** [comment]
>Could you check if there are any errors in the console?

yup, you were correct, here is the error:-

![Screenshot (361)](https://user-images.githubusercontent.com/50985033/98787038-f901cf00-2424-11eb-8c95-21f502d1c477.png)

**Comment by ricknjacky** [comment]
Thanks a ton for the help @felixfbecker :)) The V0.0.2  Works!
Great Work.

**Comment by ricknjacky** [comment]
![ezgif-6-9da31b0b0d58](https://user-images.githubusercontent.com/50985033/98789546-6fec9700-2428-11eb-8fa2-c0a6c4adbfaa.gif)


I wish to capture the pop-up that reads pitch drum, can you please help me here? as the captured svg displays a blank page

**Comment by felixfbecker** [comment]
Not without being able to inspect that page. What URL is that?

**Comment by ricknjacky** [comment]
https://musicblocks.sugarlabs.org/ 
It is a music learning website 

You have to add widgets and then the pop-up is generated on click..

**Comment by felixfbecker** [comment]
Okay, I inspected that and the page is drawing the UI on a `<canvas>`. I could implement inlining that as an image into the SVG, but the thing is that `<canvas>` is inherently a raster image, not a scalable vector graphic (SVG). This means you wouldn't get any benefit from generating a screenshot in SVG of this compared to a normal PNG screenshot (which is also a raster image). Does that make sense?

**Comment by ricknjacky** [comment]
I get it, but I am doing this to replace the deprecated svg files, like the previous ones were in svg and just some of them need replacement, so to maintain the files the way they were, is why I want to capture svg of the pop up i.e pitch drum.

**Comment by ricknjacky** [comment]
It's possible to capture the pitch drum as a svg file though, right?

**Comment by felixfbecker** [comment]
How do I trigger the popup to show what is shown in your GIF?

**Comment by ricknjacky** [comment]
![ezgif-2-42391e1be3c4](https://user-images.githubusercontent.com/50985033/98794326-eb514700-242e-11eb-9d7f-2f5db4c7c739.gif)


A laconic guide, after adding those blocks click on the drum mapper to generate the pop-up of that widget, hope this helps

**Comment by ricknjacky** [comment]
@felixfbecker Is it possible to capture the block?

**Comment by felixfbecker** [comment]
Yeah it should be possible since that is not part of the `<canvas>`. I tested it and fixed an issue that occured there - this version should work for you: https://github.com/felixfbecker/svg-screenshots/suites/1485186742/artifacts/25747222

**Comment by ricknjacky** [comment]
Solves the problem to a great extent :) thanks a lot @felixfbecker ...waiting for further updates until then :))

**Comment by felixfbecker** [comment]
FYI the new version (v0.0.2) that works for google.com is now approved and in the Store. I just submitted  v0.0.3 for review which works for the music board website.
