### ISSUE TITLE
An error happened while capturing the page: <image> element must have ID 

### ISSUE THREAD

**Issue by Mattwmaster58** [felixfbecker/svg-screenshots#53]
It's unclear why this occurs, unfortunately the only page I can recreate this with is behind some auth (and requires a costly subscription!). I tried to find `img:not([id])`, but that only yielded one result. I deleted the element, and issue persisted.
![image](https://user-images.githubusercontent.com/26337069/105130816-b52ae600-5ab5-11eb-95f9-7294688cad65.png)

**Comment by felixfbecker** [comment]
Thanks for the bug report, but it's hard to debug without a repro.
As a workaround, disabling "Inline resources" would likely work, because the error comes from within the resource-inlining logic.
